@url_dev=http://localhost:3056/v1/api

### Signup
POST {{url_dev}}/signup
Content-Type: application/json

{
    "username": "shoptips1",
    "full_name": "Shop TIPS1",
    "phone": "09134566678",
    "address": "Hanoi",
    "email": "shoptip1js@gmail.com",
    "password": "abc123"
}
